### ISSUE TITLE
Force HTTPS in GitHub Pages

### ISSUE THREAD

**Issue by Ayesh** [ThePHPF/thephp.foundation#117]
As @iluuu1994 mentioned in Slack, we apparently do not enforce HTTPS.
I think we can do so easily with a [setting](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

**Comment by pronskiy** [comment]
Thanks @Ayesh. Should be fixed now.
