### ISSUE TITLE
Contact page email failure

### ISSUE THREAD

**Issue by boxcleverliam** [ThePHPF/thephp.foundation#154]
I sent a message to the address listed on https://thephp.foundation/contact/
I got a notification that it had been blocked.
I'll include more details in screenshots, as I don't want to post the actual email addresses publicly.

![Screenshot 2024-06-10 at 1 39 10 PM](https://github.com/ThePHPF/thephp.foundation/assets/23364154/5f6a5eb7-4749-4f1f-93b2-353e02559cc0)
![Screenshot 2024-06-10 at 1 40 02 PM](https://github.com/ThePHPF/thephp.foundation/assets/23364154/da16270e-1b07-4c84-8e32-f94974b323e6)
![Screenshot 2024-06-10 at 1 41 22 PM](https://github.com/ThePHPF/thephp.foundation/assets/23364154/b16ec94c-d8a9-45b1-83e4-587aa669c949)

**Comment by pronskiy** [comment]
@boxcleverliam, oh wow. Thanks for reporting. I will take a look at it, asap.

**Comment by pronskiy** [comment]
@boxcleverliam this should be fixed now.
