### ISSUE TITLE
Add "Speakers" page

### ISSUE THREAD

**Issue by pronskiy** [ThePHPF/thephp.foundation#82]
This page should mention folks who can give talks from the PHP Foundation side, and potential topics.
Also makes sense to list recordings of the previous talks.

**Comment by sebastianbergmann** [comment]
#### The PHP Foundation: The Past, the Present, and the Future (ForumPHP 2022)

* **Material:** https://thephp.cc/presentations/the-php-foundation-the-past-the-present-and-the-future
* **Video:** https://youtu.be/JBPtPy9iSP0
